wandb_version: 1

algorithm:
  value: PPO
batch_size:
  value: 256
clip_range:
  value: 0.24168879898439252
ent_coef:
  value: 4.650180603544059e-05
gae_lambda:
  value: 0.9347924377604362
gamma:
  value: 0.9884786085181796
learning_rate:
  value: 1.1775647341040731e-05
max_steps:
  value: 700
max_velocity:
  value: 0.0426542788643342
n_envs:
  value: 2
n_steps:
  value: 2048
net_arch:
  value: 256 256
reward_scale:
  value: 3.4849161259718904
seed:
  value: 123
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.34239025755727504
