wandb_version: 1

algorithm:
  value: PPO
batch_size:
  value: 256
clip_range:
  value: 0.2010719622461408
ent_coef:
  value: 0.00016395817309377577
gae_lambda:
  value: 0.9813787375058226
gamma:
  value: 0.9928417676893364
learning_rate:
  value: 1.360201422997062e-05
max_steps:
  value: 500
max_velocity:
  value: 0.06679928337188365
n_envs:
  value: 2
n_steps:
  value: 2048
net_arch:
  value: 512 512
reward_scale:
  value: 2.545401441413379
seed:
  value: 42
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.6032045129401777
