wandb_version: 1

algorithm:
  value: SAC
batch_size:
  value: 256
clip_range:
  value: 0.16905279236084403
ent_coef:
  value: 0.03711156592778746
gae_lambda:
  value: 0.9264139469414836
gamma:
  value: 0.9587228561081436
learning_rate:
  value: 0.00012539158500540003
max_steps:
  value: 300
max_velocity:
  value: 0.0775633528280554
n_envs:
  value: 2
n_steps:
  value: 4096
net_arch:
  value: 128 128
reward_scale:
  value: 0.9070501085117704
seed:
  value: 42
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.7101330735544735
