wandb_version: 1

algorithm:
  value: SAC
batch_size:
  value: 512
clip_range:
  value: 0.3917343648118321
ent_coef:
  value: 8.740491750935531e-05
gae_lambda:
  value: 0.9122650332285208
gamma:
  value: 0.971397802972933
learning_rate:
  value: 5.339071296619955e-05
max_steps:
  value: 500
max_velocity:
  value: 0.055816835613109725
n_envs:
  value: 4
n_steps:
  value: 1024
net_arch:
  value: 128 128
reward_scale:
  value: 0.8823868881931569
seed:
  value: 42
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.3827617134992378
