wandb_version: 1

algorithm:
  value: TD3
batch_size:
  value: 256
clip_range:
  value: 0.13004426108011485
ent_coef:
  value: 0.06431397364712005
gae_lambda:
  value: 0.9804585795615228
gamma:
  value: 0.9891574960938851
learning_rate:
  value: 0.00017337869004225662
max_steps:
  value: 500
max_velocity:
  value: 0.06014338565091416
n_envs:
  value: 4
n_steps:
  value: 2048
net_arch:
  value: 512 512
reward_scale:
  value: 3.376596688759841
seed:
  value: 456
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.3120282071488883
