wandb_version: 1

algorithm:
  value: SAC
batch_size:
  value: 128
clip_range:
  value: 0.3186410147980275
ent_coef:
  value: 0.012022942732359746
gae_lambda:
  value: 0.9510479254856478
gamma:
  value: 0.9537875611927068
learning_rate:
  value: 0.0002949201993888943
max_steps:
  value: 500
max_velocity:
  value: 0.04314126286087235
n_envs:
  value: 2
n_steps:
  value: 1024
net_arch:
  value: 512 512
reward_scale:
  value: 0.732146973083442
seed:
  value: 456
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.3663676573250426
