wandb_version: 1

algorithm:
  value: SAC
batch_size:
  value: 256
clip_range:
  value: 0.2158858471626871
ent_coef:
  value: 0.08306226831481349
gae_lambda:
  value: 0.9831859039682782
gamma:
  value: 0.955205129959388
learning_rate:
  value: 4.857360338412693e-05
max_steps:
  value: 500
max_velocity:
  value: 0.053332500733312097
n_envs:
  value: 4
n_steps:
  value: 1024
net_arch:
  value: 128 128
reward_scale:
  value: 3.8332112934501583
seed:
  value: 456
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.9431488213659251
