wandb_version: 1

algorithm:
  value: TD3
batch_size:
  value: 256
clip_range:
  value: 0.10851010987802158
ent_coef:
  value: 0.0003766874302705686
gae_lambda:
  value: 0.92174343842975
gamma:
  value: 0.9779109070623284
learning_rate:
  value: 1.5185851070538995e-05
max_steps:
  value: 500
max_velocity:
  value: 0.06575609229798726
n_envs:
  value: 1
n_steps:
  value: 4096
net_arch:
  value: 256 256
reward_scale:
  value: 0.5285901938585107
seed:
  value: 456
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.7600666853068959
