wandb_version: 1

algorithm:
  value: TD3
batch_size:
  value: 256
clip_range:
  value: 0.11982770764490255
ent_coef:
  value: 1.2483501533551564e-05
gae_lambda:
  value: 0.9372630707897444
gamma:
  value: 0.9743068010484528
learning_rate:
  value: 0.0004327661549706912
max_steps:
  value: 700
max_velocity:
  value: 0.053122402297617374
n_envs:
  value: 4
n_steps:
  value: 1024
net_arch:
  value: 128 128
reward_scale:
  value: 0.5679863513198408
seed:
  value: 42
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.6851807120939616
