wandb_version: 1

algorithm:
  value: TD3
batch_size:
  value: 64
clip_range:
  value: 0.2963249821747879
ent_coef:
  value: 0.01305475520857608
gae_lambda:
  value: 0.9276384890414612
gamma:
  value: 0.9757759118261145
learning_rate:
  value: 0.0002809284571046057
max_steps:
  value: 700
max_velocity:
  value: 0.050279862421100385
n_envs:
  value: 1
n_steps:
  value: 4096
net_arch:
  value: 128 128
reward_scale:
  value: 0.5387097427555299
seed:
  value: 42
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.8078221463092957
