wandb_version: 1

algorithm:
  value: TD3
batch_size:
  value: 512
clip_range:
  value: 0.17953188992284774
ent_coef:
  value: 0.043441023901224174
gae_lambda:
  value: 0.9240317531422738
gamma:
  value: 0.9544875941771062
learning_rate:
  value: 3.8900244600978134e-05
max_steps:
  value: 300
max_velocity:
  value: 0.03970168163464805
n_envs:
  value: 2
n_steps:
  value: 1024
net_arch:
  value: 512 512
reward_scale:
  value: 0.5290628577594868
seed:
  value: 42
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.6909994631536093
