wandb_version: 1

algorithm:
  value: PPO
batch_size:
  value: 64
clip_range:
  value: 0.3387619079508328
ent_coef:
  value: 0.0009307916835267396
gae_lambda:
  value: 0.9760500700920636
gamma:
  value: 0.995538261016133
learning_rate:
  value: 0.00013386291753757324
max_steps:
  value: 700
max_velocity:
  value: 0.05107823975563197
n_envs:
  value: 2
n_steps:
  value: 2048
net_arch:
  value: 256 256
reward_scale:
  value: 0.7779759870218683
seed:
  value: 456
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.9683096582748464
