wandb_version: 1

algorithm:
  value: TD3
batch_size:
  value: 512
clip_range:
  value: 0.2499869387526044
ent_coef:
  value: 2.4137886607030664e-05
gae_lambda:
  value: 0.9477861660894212
gamma:
  value: 0.9972812505756544
learning_rate:
  value: 0.0005401708797330223
max_steps:
  value: 500
max_velocity:
  value: 0.0345914242883125
n_envs:
  value: 2
n_steps:
  value: 4096
net_arch:
  value: 512 512
reward_scale:
  value: 1.6120320275629043
seed:
  value: 42
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.9013442281125668
