wandb_version: 1

algorithm:
  value: PPO
batch_size:
  value: 64
clip_range:
  value: 0.21872925239443208
ent_coef:
  value: 0.003699571189239272
gae_lambda:
  value: 0.9101458570960604
gamma:
  value: 0.9770591841763682
learning_rate:
  value: 0.00025932404610651586
max_steps:
  value: 300
max_velocity:
  value: 0.05446245983096709
n_envs:
  value: 1
n_steps:
  value: 4096
net_arch:
  value: 128 128
reward_scale:
  value: 3.594538181972366
seed:
  value: 456
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.9834733903549016
