wandb_version: 1

algorithm:
  value: TD3
batch_size:
  value: 128
clip_range:
  value: 0.23528410509497263
ent_coef:
  value: 0.00040049194986582233
gae_lambda:
  value: 0.9819383721050976
gamma:
  value: 0.9921668939903818
learning_rate:
  value: 0.0001923594233009824
max_steps:
  value: 700
max_velocity:
  value: 0.06095097620314467
n_envs:
  value: 4
n_steps:
  value: 2048
net_arch:
  value: 256 256
reward_scale:
  value: 1.3620462717263635
seed:
  value: 456
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.9001373699849546
