wandb_version: 1

algorithm:
  value: TD3
batch_size:
  value: 512
clip_range:
  value: 0.15024116969191215
ent_coef:
  value: 0.00014817621038529387
gae_lambda:
  value: 0.986261763281836
gamma:
  value: 0.969458136714279
learning_rate:
  value: 0.0008520527804877439
max_steps:
  value: 300
max_velocity:
  value: 0.05272531824705168
n_envs:
  value: 4
n_steps:
  value: 4096
net_arch:
  value: 128 128
reward_scale:
  value: 2.452554396143266
seed:
  value: 123
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.12353342916156758
