wandb_version: 1

algorithm:
  value: PPO
batch_size:
  value: 512
clip_range:
  value: 0.1377592091204774
ent_coef:
  value: 2.4146686159079217e-05
gae_lambda:
  value: 0.9782867504732125
gamma:
  value: 0.9618603150172612
learning_rate:
  value: 0.0008459278893964176
max_steps:
  value: 500
max_velocity:
  value: 0.06880960514732681
n_envs:
  value: 4
n_steps:
  value: 4096
net_arch:
  value: 128 128
reward_scale:
  value: 1.5729182407522917
seed:
  value: 42
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.6791478512172152
