wandb_version: 1

algorithm:
  value: SAC
batch_size:
  value: 256
clip_range:
  value: 0.2491737656409977
ent_coef:
  value: 0.0009399991484757608
gae_lambda:
  value: 0.9238036594592822
gamma:
  value: 0.95532976429463
learning_rate:
  value: 6.877263258185408e-05
max_steps:
  value: 300
max_velocity:
  value: 0.034302735018717334
n_envs:
  value: 1
n_steps:
  value: 4096
net_arch:
  value: 128 128
reward_scale:
  value: 3.8622375245700056
seed:
  value: 42
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.9443396796637928
