wandb_version: 1

algorithm:
  value: PPO
batch_size:
  value: 64
clip_range:
  value: 0.31129320645531233
ent_coef:
  value: 0.00011252237718714918
gae_lambda:
  value: 0.9340371473483616
gamma:
  value: 0.964598826975464
learning_rate:
  value: 0.0007492113238653973
max_steps:
  value: 300
max_velocity:
  value: 0.06507823999872137
n_envs:
  value: 2
n_steps:
  value: 4096
net_arch:
  value: 512 512
reward_scale:
  value: 3.5361682086739066
seed:
  value: 42
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.12574564216337047
