wandb_version: 1

algorithm:
  value: TD3
batch_size:
  value: 128
clip_range:
  value: 0.2266433578772378
ent_coef:
  value: 1.3350872924450904e-05
gae_lambda:
  value: 0.9750214620698678
gamma:
  value: 0.9714977503979896
learning_rate:
  value: 3.93599171578016e-05
max_steps:
  value: 300
max_velocity:
  value: 0.040601705697405906
n_envs:
  value: 1
n_steps:
  value: 2048
net_arch:
  value: 128 128
reward_scale:
  value: 3.3512511111451952
seed:
  value: 42
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.5300374198928164
