wandb_version: 1

algorithm:
  value: SAC
batch_size:
  value: 512
clip_range:
  value: 0.3547624018965181
ent_coef:
  value: 0.00010878090018178752
gae_lambda:
  value: 0.9060323446295716
gamma:
  value: 0.97589765623458
learning_rate:
  value: 0.00032709043616453953
max_steps:
  value: 300
max_velocity:
  value: 0.07890138534546369
n_envs:
  value: 2
n_steps:
  value: 2048
net_arch:
  value: 512 512
reward_scale:
  value: 2.073982990737491
seed:
  value: 123
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.6738866640290263
