wandb_version: 1

algorithm:
  value: SAC
batch_size:
  value: 256
clip_range:
  value: 0.3548706770304386
ent_coef:
  value: 0.00010824997678130992
gae_lambda:
  value: 0.9895906390773112
gamma:
  value: 0.9937213489498712
learning_rate:
  value: 0.0001106973542095688
max_steps:
  value: 700
max_velocity:
  value: 0.03445285403620503
n_envs:
  value: 4
n_steps:
  value: 4096
net_arch:
  value: 512 512
reward_scale:
  value: 1.136096720883973
seed:
  value: 123
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.8034301471578587
