wandb_version: 1

algorithm:
  value: PPO
batch_size:
  value: 128
clip_range:
  value: 0.3253047019886593
ent_coef:
  value: 7.893824476142776e-05
gae_lambda:
  value: 0.9537818892744676
gamma:
  value: 0.9530169822323258
learning_rate:
  value: 0.0001341792479147414
max_steps:
  value: 700
max_velocity:
  value: 0.06739032192113983
n_envs:
  value: 4
n_steps:
  value: 2048
net_arch:
  value: 128 128
reward_scale:
  value: 0.7498812418953616
seed:
  value: 42
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.507046603890829
