wandb_version: 1

algorithm:
  value: PPO
batch_size:
  value: 64
clip_range:
  value: 0.22015936528296476
ent_coef:
  value: 0.03288045317663377
gae_lambda:
  value: 0.9053026064633636
gamma:
  value: 0.969582861483016
learning_rate:
  value: 0.0001577967736355408
max_steps:
  value: 700
max_velocity:
  value: 0.05778015339617343
n_envs:
  value: 4
n_steps:
  value: 1024
net_arch:
  value: 128 128
reward_scale:
  value: 0.6810978147924955
seed:
  value: 456
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.3096462220115145
