wandb_version: 1

algorithm:
  value: SAC
batch_size:
  value: 512
clip_range:
  value: 0.3739354970269435
ent_coef:
  value: 0.05010567392267294
gae_lambda:
  value: 0.9408123596309084
gamma:
  value: 0.9746141930404828
learning_rate:
  value: 2.6846852130718208e-05
max_steps:
  value: 700
max_velocity:
  value: 0.03685347884146346
n_envs:
  value: 2
n_steps:
  value: 1024
net_arch:
  value: 256 256
reward_scale:
  value: 3.5909077853622815
seed:
  value: 42
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.8121379166433947
