wandb_version: 1

algorithm:
  value: TD3
batch_size:
  value: 256
clip_range:
  value: 0.28852441961603087
ent_coef:
  value: 0.0017470064685635323
gae_lambda:
  value: 0.9805339378303232
gamma:
  value: 0.977531685289814
learning_rate:
  value: 5.4943912166649714e-05
max_steps:
  value: 300
max_velocity:
  value: 0.06935923959851326
n_envs:
  value: 1
n_steps:
  value: 4096
net_arch:
  value: 512 512
reward_scale:
  value: 1.7226234663989966
seed:
  value: 42
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.8490650665871351
