wandb_version: 1

algorithm:
  value: SAC
batch_size:
  value: 512
clip_range:
  value: 0.30148503276263194
ent_coef:
  value: 0.05788403891870998
gae_lambda:
  value: 0.9436188525264896
gamma:
  value: 0.9608310845164656
learning_rate:
  value: 9.657695085303808e-05
max_steps:
  value: 500
max_velocity:
  value: 0.07790057975700734
n_envs:
  value: 2
n_steps:
  value: 4096
net_arch:
  value: 256 256
reward_scale:
  value: 0.5906861925057356
seed:
  value: 456
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.24448215164899215
