wandb_version: 1

algorithm:
  value: SAC
batch_size:
  value: 256
clip_range:
  value: 0.13690866059552118
ent_coef:
  value: 0.02305260821680862
gae_lambda:
  value: 0.977669973953344
gamma:
  value: 0.9712749041574242
learning_rate:
  value: 1.804044529046291e-05
max_steps:
  value: 500
max_velocity:
  value: 0.071361827949425
n_envs:
  value: 1
n_steps:
  value: 1024
net_arch:
  value: 256 256
reward_scale:
  value: 0.6207753915558518
seed:
  value: 456
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.5188476840778834
