wandb_version: 1

algorithm:
  value: PPO
batch_size:
  value: 128
clip_range:
  value: 0.19924564385592825
ent_coef:
  value: 0.0017091492730628695
gae_lambda:
  value: 0.9330987544610752
gamma:
  value: 0.9791196482742762
learning_rate:
  value: 0.00027769240012200493
max_steps:
  value: 300
max_velocity:
  value: 0.033911816568195176
n_envs:
  value: 2
n_steps:
  value: 4096
net_arch:
  value: 512 512
reward_scale:
  value: 2.760064108348542
seed:
  value: 123
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.4870169770300437
