wandb_version: 1

algorithm:
  value: PPO
batch_size:
  value: 512
clip_range:
  value: 0.1732188880782072
ent_coef:
  value: 5.648808349670434e-05
gae_lambda:
  value: 0.9751283122138406
gamma:
  value: 0.9756608019863802
learning_rate:
  value: 1.7526847071492808e-05
max_steps:
  value: 700
max_velocity:
  value: 0.03418087153049202
n_envs:
  value: 1
n_steps:
  value: 2048
net_arch:
  value: 512 512
reward_scale:
  value: 1.2229902400838677
seed:
  value: 42
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.3429371976941318
