wandb_version: 1

algorithm:
  value: PPO
batch_size:
  value: 512
clip_range:
  value: 0.13354661744114013
ent_coef:
  value: 0.0019823838618278347
gae_lambda:
  value: 0.954937917107332
gamma:
  value: 0.9833380449039716
learning_rate:
  value: 0.00021528245549035256
max_steps:
  value: 500
max_velocity:
  value: 0.06865047627903201
n_envs:
  value: 1
n_steps:
  value: 2048
net_arch:
  value: 128 128
reward_scale:
  value: 1.5374288376571326
seed:
  value: 42
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.21071546378348693
