wandb_version: 1

algorithm:
  value: TD3
batch_size:
  value: 64
clip_range:
  value: 0.3277489162878046
ent_coef:
  value: 0.017099407049769758
gae_lambda:
  value: 0.936042026338314
gamma:
  value: 0.9923523143343366
learning_rate:
  value: 5.667030471275399e-05
max_steps:
  value: 300
max_velocity:
  value: 0.056018464700320326
n_envs:
  value: 2
n_steps:
  value: 2048
net_arch:
  value: 512 512
reward_scale:
  value: 3.3870606075583836
seed:
  value: 42
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.6780886954100578
