wandb_version: 1

algorithm:
  value: TD3
batch_size:
  value: 512
clip_range:
  value: 0.1503033584935064
ent_coef:
  value: 0.008810688307956647
gae_lambda:
  value: 0.9461712033490964
gamma:
  value: 0.9603238366609914
learning_rate:
  value: 0.0005530190350776668
max_steps:
  value: 700
max_velocity:
  value: 0.06702283113228558
n_envs:
  value: 1
n_steps:
  value: 4096
net_arch:
  value: 512 512
reward_scale:
  value: 0.6163300653051013
seed:
  value: 42
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.6173778915003624
