wandb_version: 1

algorithm:
  value: TD3
batch_size:
  value: 64
clip_range:
  value: 0.355498071581384
ent_coef:
  value: 0.001269854814184654
gae_lambda:
  value: 0.9251092167395044
gamma:
  value: 0.990741251483826
learning_rate:
  value: 0.00020427805860707377
max_steps:
  value: 500
max_velocity:
  value: 0.06261674325758582
n_envs:
  value: 4
n_steps:
  value: 1024
net_arch:
  value: 512 512
reward_scale:
  value: 0.8948596584693695
seed:
  value: 456
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.7968059019437547
