wandb_version: 1

algorithm:
  value: SAC
batch_size:
  value: 512
clip_range:
  value: 0.39475429361488734
ent_coef:
  value: 0.0004981683218089227
gae_lambda:
  value: 0.9857258362010995
gamma:
  value: 0.9783453344690528
learning_rate:
  value: 0.0007083819645485583
max_steps:
  value: 500
max_velocity:
  value: 0.07472619470676958
n_envs:
  value: 2
n_steps:
  value: 4096
net_arch:
  value: 128 128
reward_scale:
  value: 2.354286445181806
seed:
  value: 456
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.5547693882605111
