wandb_version: 1

algorithm:
  value: PPO
batch_size:
  value: 512
clip_range:
  value: 0.1763690605163431
ent_coef:
  value: 0.0007299551123765656
gae_lambda:
  value: 0.941386658603718
gamma:
  value: 0.9840002426455724
learning_rate:
  value: 0.0002470479230785572
max_steps:
  value: 700
max_velocity:
  value: 0.06790951296521552
n_envs:
  value: 2
n_steps:
  value: 4096
net_arch:
  value: 128 128
reward_scale:
  value: 4.31112392672931
seed:
  value: 456
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.27242630519640276
