wandb_version: 1

algorithm:
  value: SAC
batch_size:
  value: 512
clip_range:
  value: 0.14238550876260786
ent_coef:
  value: 0.0008517060379197698
gae_lambda:
  value: 0.9651164024545168
gamma:
  value: 0.9701507589429982
learning_rate:
  value: 1.6973438633023646e-05
max_steps:
  value: 700
max_velocity:
  value: 0.060387979785546025
n_envs:
  value: 2
n_steps:
  value: 1024
net_arch:
  value: 512 512
reward_scale:
  value: 2.877832410218788
seed:
  value: 42
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.3592721703523093
