wandb_version: 1

algorithm:
  value: TD3
batch_size:
  value: 256
clip_range:
  value: 0.11028751941529048
ent_coef:
  value: 0.003904530964360527
gae_lambda:
  value: 0.986009532598209
gamma:
  value: 0.9516797546380282
learning_rate:
  value: 0.00027506694814010844
max_steps:
  value: 300
max_velocity:
  value: 0.06990644838298728
n_envs:
  value: 4
n_steps:
  value: 4096
net_arch:
  value: 512 512
reward_scale:
  value: 0.7621177191742275
seed:
  value: 123
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.6972134002962947
