wandb_version: 1

algorithm:
  value: TD3
batch_size:
  value: 128
clip_range:
  value: 0.22424418583589056
ent_coef:
  value: 1.0836815679313909e-05
gae_lambda:
  value: 0.9146565942856136
gamma:
  value: 0.9729999740529386
learning_rate:
  value: 5.679531176269811e-05
max_steps:
  value: 300
max_velocity:
  value: 0.07048696544726939
n_envs:
  value: 1
n_steps:
  value: 2048
net_arch:
  value: 256 256
reward_scale:
  value: 0.8497557298017353
seed:
  value: 42
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.9360338335062884
