wandb_version: 1

algorithm:
  value: SAC
batch_size:
  value: 128
clip_range:
  value: 0.13293002960244657
ent_coef:
  value: 0.002001918133868851
gae_lambda:
  value: 0.9136099587059202
gamma:
  value: 0.9978984929684386
learning_rate:
  value: 0.000992402970915519
max_steps:
  value: 300
max_velocity:
  value: 0.054133815214620226
n_envs:
  value: 4
n_steps:
  value: 4096
net_arch:
  value: 512 512
reward_scale:
  value: 1.6758149562986735
seed:
  value: 42
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.635107009240021
