wandb_version: 1

algorithm:
  value: PPO
batch_size:
  value: 128
clip_range:
  value: 0.1307403848152487
ent_coef:
  value: 0.0006613148638962317
gae_lambda:
  value: 0.9354807473594952
gamma:
  value: 0.9542271337178132
learning_rate:
  value: 3.79163303375897e-05
max_steps:
  value: 700
max_velocity:
  value: 0.03328287177922146
n_envs:
  value: 2
n_steps:
  value: 2048
net_arch:
  value: 128 128
reward_scale:
  value: 1.9523747254280488
seed:
  value: 42
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.9434618539267124
