wandb_version: 1

algorithm:
  value: SAC
batch_size:
  value: 512
clip_range:
  value: 0.38211636211965505
ent_coef:
  value: 0.0002291586946667569
gae_lambda:
  value: 0.92902458593755
gamma:
  value: 0.9696784014590644
learning_rate:
  value: 0.0002394838043859287
max_steps:
  value: 300
max_velocity:
  value: 0.06973976571044482
n_envs:
  value: 4
n_steps:
  value: 2048
net_arch:
  value: 128 128
reward_scale:
  value: 1.863463721215601
seed:
  value: 123
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.26200477724972393
