wandb_version: 1

algorithm:
  value: SAC
batch_size:
  value: 512
clip_range:
  value: 0.361428908555949
ent_coef:
  value: 0.04454254674252543
gae_lambda:
  value: 0.9373900845139344
gamma:
  value: 0.9891791215468718
learning_rate:
  value: 0.0005751882334891095
max_steps:
  value: 500
max_velocity:
  value: 0.05221700202167408
n_envs:
  value: 1
n_steps:
  value: 4096
net_arch:
  value: 256 256
reward_scale:
  value: 2.9783006799594265
seed:
  value: 456
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.21429950517430357
