wandb_version: 1

algorithm:
  value: TD3
batch_size:
  value: 512
clip_range:
  value: 0.20663422657742253
ent_coef:
  value: 0.015572549926047384
gae_lambda:
  value: 0.9771857260033012
gamma:
  value: 0.9689894433688075
learning_rate:
  value: 1.326197210730236e-05
max_steps:
  value: 300
max_velocity:
  value: 0.05814328861141918
n_envs:
  value: 4
n_steps:
  value: 1024
net_arch:
  value: 512 512
reward_scale:
  value: 3.6856535812363886
seed:
  value: 42
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.2953887286979782
