wandb_version: 1

algorithm:
  value: SAC
batch_size:
  value: 64
clip_range:
  value: 0.15230601716598957
ent_coef:
  value: 0.0017359647721470822
gae_lambda:
  value: 0.9159736291545164
gamma:
  value: 0.9711595656930077
learning_rate:
  value: 0.00027188231052677236
max_steps:
  value: 300
max_velocity:
  value: 0.07270796203323747
n_envs:
  value: 2
n_steps:
  value: 2048
net_arch:
  value: 512 512
reward_scale:
  value: 1.1953728434796445
seed:
  value: 456
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.14621392676883288
