wandb_version: 1

algorithm:
  value: PPO
batch_size:
  value: 128
clip_range:
  value: 0.14011344594424296
ent_coef:
  value: 0.06169827956906807
gae_lambda:
  value: 0.9314379139465002
gamma:
  value: 0.976976230197763
learning_rate:
  value: 0.0008283822775883412
max_steps:
  value: 300
max_velocity:
  value: 0.046857396778970856
n_envs:
  value: 4
n_steps:
  value: 2048
net_arch:
  value:
  - 128
  - 128
reward_scale:
  value: 0.9410529387819296
seed:
  value: 456
success_threshold:
  value: 0.005
total_timesteps:
  value: 1000000
vf_coef:
  value: 0.5967133553863023
